### ISSUE TITLE
Doesn`t work with dynamic size 

### ISSUE THREAD

**Issue by morkov4o** [intaro/nginx-image-filter-watermark#10]
Hi, 

when i try to make resize or crop with a specific dimensions it works. But when i try to resize on a dynamic height for example 400 - it doesn't add the watermark. Any idea ?

Thanks

**Comment by hermitson** [comment]
I am....

**Comment by hermitson** [comment]
@grigoryangeo help

**Comment by hermitson** [comment]
![image](https://user-images.githubusercontent.com/24245864/32004136-a746c3f0-b9d3-11e7-9f0c-b29cdb9e18e1.png)
nginx.conf

**Comment by morkov4o** [comment]
are you facing the same problem ?

**Comment by hermitson** [comment]
yes,Have you solved it?

**Comment by morkov4o** [comment]
nope, still trying to do it.

**Comment by hermitson** [comment]
I am,if you solved,please tell me...THanks

**Comment by hermitson** [comment]
Eventually the problem is resolved。
![image](https://user-images.githubusercontent.com/24245864/32031818-08013e2a-ba36-11e7-9059-e495d141ab77.png)

**Comment by morkov4o** [comment]
and how this fix the problem with the dynamic width/height ? 
I mean when you send something like this resize/600/- or resize/-/600

**Comment by morkov4o** [comment]
@grigoryangeo please help ..

**Comment by grigoryangeo** [comment]
Hi, dynamic width/height not be work now. I'll think about how to solve this issue

**Comment by morkov4o** [comment]
@grigoryangeo any update on this ?

**Comment by morkov4o** [comment]
up

**Comment by grigoryangeo** [comment]
Good news, I'm back in the ranks. Next week I will solve

**Comment by grigoryangeo** [comment]
fix it
