### ISSUE TITLE
If source image, PNG or GIF, have transparency, after apply watermark, destination image have black rectangle on background.

### ISSUE THREAD

**Issue by deepdivenow** [intaro/nginx-image-filter-watermark#13]
Hi

If source image, PNG or GIF, have transparency, after apply watermark, destination image have black rectangle on background.

bad image example: https://ibb.co/moGmqy

I don't have big experience in GD library, maybe you know fine decition to solve this problem?

I have created pull request this possible solution for example.
https://github.com/intaro/nginx-image-filter-watermark/pull/12

**Comment by grigoryangeo** [comment]
thanks
