### ISSUE TITLE
Video watermark

### ISSUE THREAD

**Issue by elibushehri** [intaro/nginx-image-filter-watermark#6]
Hi 
Is there any patch for video watermarking in nginx?
I just know about ffmpeg command in nginx config but it takes too long to answer.
do you have any idea?
thnaks

**Comment by grigoryangeo** [comment]
Hi, 
This patch will not work exactly, handles only images.  I think nginx have no such functional. Processing video while playing a very expensive operation, i think in your case is more appropriate background processing video. 

You can see the source code http://nginx.org/en/docs/http/ngx_http_mp4_module.html, perhaps can be modified
